/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class NodeTest{
    @Test public void testNodeReadout(){
        Node seven = makeTestTree();
        String actual   = seven.toString();
        System.out.println(actual);
        String expected = "7:{4:{3, }, 10:{8, 22}}";
        assertEquals(expected, actual);
    }

    @Test public void testInvalidBST(){
        Node seven = new Node(7);
        seven.setLeft(new Node(4));
        seven.getLeft().setLeft(new Node(3));
        seven.setRight(new Node(10));
        seven.getRight().setLeft(new Node(8));
        seven.getRight().setRight(new Node(9));
        assertFalse(seven.isValidBST());
    }

    @Test public void testInsert(){
        Node seven = makeTestTree();
        String actual   = seven.toString();
        System.out.println(actual);
        seven.insert(new Node(5));
        String expected = "7:{4:{3, 5}, 10:{8, 22}}";
        assertEquals(expected, actual);
    }
    @Test public void testRotateOnRight(){
        Node seven = makeTestTree();
        BST bst = new BST(new Node(2));
        bst.insert(seven);
        System.out.println(bst);
        bst.rotateUp(seven.getRight());
        System.out.println(bst);
        assertTrue(bst.getRoot().isValidBST());
        String expected = "2:{, 10:{7:{4:{3, }, 8}, 22}}";
        assertEquals(bst.getRoot().toString(), expected);
    }

    private Node makeTestTree(){
        Node seven = new Node(7);
        seven.insert(new Node(4));
        seven.insert(new Node(3));
        seven.insert(new Node(10));
        seven.insert(new Node(8));
        seven.insert(new Node(22));
        return seven;
    }

}
